<?xml version="1.0" encoding="utf-8"?>
<Database Name="webmech" Class="WebMechDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PETR-W7\SQLEXPRESS;Initial Catalog=webmech;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="webmechConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Surface" Member="Surfaces">
    <Type Name="Surface">
      <Column Name="surface_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="creation_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modification_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Surface_Sample" Member="Samples" ThisKey="surface_id" OtherKey="surface_id" Type="Sample" />
    </Type>
  </Table>
  <Table Name="dbo.Sample" Member="Samples">
    <Type Name="Sample">
      <Column Name="sample_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="surface_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="sample_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="upload_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modification_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="filename" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Sample_Point" Member="Points" ThisKey="sample_id" OtherKey="sample_id" Type="Point" />
      <Association Name="Sample_Parameter" Member="Parameters" ThisKey="sample_id" OtherKey="sample_id" Type="Parameter" />
      <Association Name="Sample_Statistic" Member="Statistic" ThisKey="sample_id" OtherKey="sample_id" Type="Statistic" Cardinality="One" />
      <Association Name="Surface_Sample" Member="Surface" ThisKey="surface_id" OtherKey="surface_id" Type="Surface" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Point" Member="Points">
    <Type Name="Point">
      <Column Name="sample_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[order]" Member="order" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="x" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="y" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="z" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Sample_Point" Member="Sample" ThisKey="sample_id" OtherKey="sample_id" Type="Sample" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Parameter" Member="Parameters">
    <Type Name="Parameter">
      <Column Name="sample_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[order]" Member="order" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="value" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Sample_Parameter" Member="Sample" ThisKey="sample_id" OtherKey="sample_id" Type="Sample" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Statistic" Member="Statistics">
    <Type Name="Statistic">
      <Column Name="sample_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="x_min" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="x_max" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="y_min" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="y_max" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="z_min" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="z_max" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="z_mean" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Sample_Statistic" Member="Sample" ThisKey="sample_id" OtherKey="sample_id" Type="Sample" IsForeignKey="true" />
    </Type>
  </Table>
</Database>