prompt /* 14 - SYSTEM */;
DROP TRIGGER SET_TMAPPER_WS_SYSTEM_id;
DROP SEQUENCE TMAPPER_WS_SYSTEM_id_SEQ;
DROP TABLE TMAPPER_WS_SYSTEM CASCADE CONSTRAINTS;

prompt /* 13 - EQUIPMENT */;
DROP TRIGGER SET_TMAPPER_WS_EQUIPMENT_id;
DROP SEQUENCE TMAPPER_WS_EQUIPMENT_id_SEQ;
DROP TABLE TMAPPER_WS_EQUIPMENT CASCADE CONSTRAINTS;

prompt /* 12 - EQUIPMENT_TYPE */;
DROP TRIGGER SET_TMAPPER_WS_EQUIPMENT_TY_id;
DROP SEQUENCE TMAPPER_WS_EQUIPMENT_TY_id_SEQ;
DROP TABLE TMAPPER_WS_EQUIPMENT_TYPE CASCADE CONSTRAINTS;

prompt /* 11 - PLATFORM */;
DROP TRIGGER SET_TMAPPER_WS_PLATFORM_id;
DROP SEQUENCE TMAPPER_WS_PLATFORM_id_SEQ;
DROP TABLE TMAPPER_WS_PLATFORM CASCADE CONSTRAINTS;

prompt /* 10 - CFG_DATA */;
DROP TRIGGER SET_TMAPPER_WS_CFG_DATA_id;
DROP SEQUENCE TMAPPER_WS_CFG_DATA_id_SEQ;
DROP TABLE TMAPPER_WS_CFG_DATA CASCADE CONSTRAINTS;

prompt /* 9 - CFG_TEMPLATE */;
DROP TRIGGER SET_TMAPPER_WS_CFG_TEMPLATE_id;
DROP SEQUENCE TMAPPER_WS_CFG_TEMPLATE_id_SEQ;
DROP TABLE TMAPPER_WS_CFG_TEMPLATE CASCADE CONSTRAINTS;

prompt /* 8 - CFG_TEMPLATE */;
DROP TRIGGER SET_TMAPPER_WS_CFG_TEMPLKEY_id;
DROP SEQUENCE TMAPPER_WS_CFG_TEMPLKEY_id_SEQ;
DROP TABLE TMAPPER_WS_CFG_TEMPLATE_KEY CASCADE CONSTRAINTS;

prompt /* 7 - CFG_KEY */;
DROP TRIGGER SET_TMAPPER_WS_CFG_KEY_id;
DROP SEQUENCE TMAPPER_WS_CFG_KEY_id_SEQ;
DROP TABLE TMAPPER_WS_CFG_KEY CASCADE CONSTRAINTS;

prompt /* 6 - CFG_DATA_TYPE */;
DROP TRIGGER SET_TMAPPER_WS_CFG_DATA_TYP_id;
DROP SEQUENCE TMAPPER_WS_CFG_DATA_TYP_id_SEQ;
DROP TABLE TMAPPER_WS_CFG_DATA_TYPE CASCADE CONSTRAINTS;

prompt /* 5 - CFG_TYPE */;
DROP TRIGGER SET_TMAPPER_WS_CFG_TYPE_id;
DROP SEQUENCE TMAPPER_WS_CFG_TYPE_id_SEQ;
DROP TABLE TMAPPER_WS_CFG_TYPE CASCADE CONSTRAINTS;

prompt /* 4 - CONFIGURATION */;
DROP TRIGGER SET_TMAPPER_WS_CONFIGURATIO_id;
DROP SEQUENCE TMAPPER_WS_CONFIGURATIO_id_SEQ;
DROP TABLE TMAPPER_WS_CONFIGURATION CASCADE CONSTRAINTS;

prompt /* 3 - CFG_LEVEL */;
DROP TRIGGER SET_TMAPPER_WS_CFG_LEVEL_id;
DROP SEQUENCE TMAPPER_WS_CFG_LEVEL_id_SEQ;
DROP TABLE TMAPPER_WS_CFG_LEVEL CASCADE CONSTRAINTS;

prompt /* 2 - MAPPER_VERSION */;
DROP TRIGGER SET_TMAPPER_WS_MAPPER_VERSI_id;
DROP SEQUENCE TMAPPER_WS_MAPPER_VERSI_id_SEQ;
DROP TABLE TMAPPER_WS_MAPPER_VERSION CASCADE CONSTRAINTS;

prompt /* 1 - CFG_VERSION */;
DROP TRIGGER SET_TMAPPER_WS_CFG_VERSION_id;
DROP SEQUENCE TMAPPER_WS_CFG_VERSION_id_SEQ;
DROP TABLE TMAPPER_WS_CFG_VERSION CASCADE CONSTRAINTS;

