/* This cript creates Mapper structures for store user privileges  */
/* (Add tablespace names to create statements if it is required) */

prompt Enter data tablespace name:
define data_ts = '&1' 

prompt Creating data structure ...

set define &

/*
DROP TABLE TMAPPER_PRIVILEGES CASCADE CONSTRAINTS
;
DROP TABLE TMAPPER_ROLE_PRIVILEGES CASCADE CONSTRAINTS
;
DROP TABLE TMAPPER_ROLES CASCADE CONSTRAINTS
;
DROP TABLE TMAPPER_USER_ROLES CASCADE CONSTRAINTS
;
DROP TABLE TMAPPER_USERS CASCADE CONSTRAINTS
;

drop sequence seq_tmapper_user_id;

drop sequence seq_tmapper_role_id;

drop sequence seq_tmapper_privilege_id;
*/

CREATE TABLE TMAPPER_PRIVILEGES ( 
	ID NUMBER(38) NOT NULL,
	NAME VARCHAR2(100) NOT NULL,
	DESCRIPTION VARCHAR2(1000)
) TABLESPACE &data_ts
;

CREATE TABLE TMAPPER_ROLE_PRIVILEGES ( 
	ID_ROLE NUMBER(38) NOT NULL,
	ID_PRIVILEGE NUMBER(38) NOT NULL
) TABLESPACE &data_ts
;

CREATE TABLE TMAPPER_ROLES ( 
	ID NUMBER(38) NOT NULL,
	NAME VARCHAR2(100) NOT NULL,
	DESCRIPTION VARCHAR2(1000)
) TABLESPACE &data_ts
;

CREATE TABLE TMAPPER_USER_ROLES ( 
	ID_USER NUMBER(38) NOT NULL,
	ID_ROLE NUMBER(38) NOT NULL
) TABLESPACE &data_ts
;

CREATE TABLE TMAPPER_USERS ( 
	ID NUMBER(38) NOT NULL,
	ON_USER_ID VARCHAR2(10) NOT NULL,
	FULL_NAME VARCHAR2(100),
	DESCRIPTION VARCHAR2(1000)
) TABLESPACE &data_ts
;


ALTER TABLE TMAPPER_PRIVILEGES ADD CONSTRAINT PK_TMAPPER_PRIVILEGES 
	PRIMARY KEY (ID)
;

ALTER TABLE TMAPPER_ROLE_PRIVILEGES ADD CONSTRAINT PK_TMAPPER_ROLE_PRIVILEGES 
	PRIMARY KEY (ID_ROLE, ID_PRIVILEGE)
;

ALTER TABLE TMAPPER_ROLES ADD CONSTRAINT PK_TMAPPER_ROLES 
	PRIMARY KEY (ID)
;

ALTER TABLE TMAPPER_USER_ROLES ADD CONSTRAINT PK_TMAPPER_USER_ROLES 
	PRIMARY KEY (ID_USER, ID_ROLE)
;

ALTER TABLE TMAPPER_USERS ADD CONSTRAINT PK_TMAPPER_USERS 
	PRIMARY KEY (ID)
;


ALTER TABLE TMAPPER_PRIVILEGES
	ADD CONSTRAINT UQ_TMAPPER_PRIVILEGES_NAME UNIQUE (NAME)
;

ALTER TABLE TMAPPER_ROLES
	ADD CONSTRAINT UQ_TMAPPER_ROLES_NAME UNIQUE (NAME)
;

ALTER TABLE TMAPPER_USERS
	ADD CONSTRAINT UQ_TMAPPER_USERS_ON_USER_ID UNIQUE (ON_USER_ID)
;



ALTER TABLE TMAPPER_ROLE_PRIVILEGES ADD CONSTRAINT FK_ROLE_PRIVS__PRIVILEGES 
	FOREIGN KEY (ID_PRIVILEGE) REFERENCES TMAPPER_PRIVILEGES (ID)
;

ALTER TABLE TMAPPER_ROLE_PRIVILEGES ADD CONSTRAINT FK_ROLE_PRIVS__ROLES 
	FOREIGN KEY (ID_ROLE) REFERENCES TMAPPER_ROLES (ID)
;

ALTER TABLE TMAPPER_USER_ROLES ADD CONSTRAINT FK_USER_ROLES__ROLES 
	FOREIGN KEY (ID_ROLE) REFERENCES TMAPPER_ROLES (ID)
;

ALTER TABLE TMAPPER_USER_ROLES ADD CONSTRAINT FK_USER_ROLES__USERS 
	FOREIGN KEY (ID_USER) REFERENCES TMAPPER_USERS (ID)
;


create sequence seq_tmapper_user_id start with 1 nocache;

create sequence seq_tmapper_role_id start with 1 nocache;

create sequence seq_tmapper_privilege_id start with 1 nocache;


